### ISSUE TITLE
Document Update needed

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/documentation#32] opened 2020-01-22 08:57 UTC
**Is this a BUG REPORT or NEW REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind new-documentation

**What happened**:
Document Name: _index.md
Document Path / Location: documentation/content/guides/user-guides/telemetry/
(Like from website/github etc - give the complete link)
Issue Faced / Error in the documentation:
The format of the head is not correct:
![screenshot](https://user-images.githubusercontent.com/9812744/72879594-31baa580-3d38-11ea-9a75-b69048bfd796.PNG)

**What you expected to happen**:
The format of the head should be correct.

**How to reproduce it (as minimally and precisely as possible)**:
Please confirm the steps followed and issue observed

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- locale of the OS: 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by anvithks** [comment] 2020-01-27 16:16
@ThisIsClark The documentation is maintained on the website [https://docs.opensds.io](https://docs.opensds.io). 
To access the page in question you have to access the link [here](https://docs.opensds.io/guides/user-guides/telemetry/).  
Since the documentation website is generated using Hugo / Netlify you will not see the same formatting if you open the source file from the content/ folder. What you have pointed out above are the `frontmatter` needed for the Hugo formatting.  
Closing since this is not a bug.

**Closed by anvithks** 2020-01-27 16:16 UTC
Labels: invalid
